### ISSUE TITLE
Least squares test seems to crash with multiple partitions

### ISSUE THREAD

**Issue by karthik-shanmugam** [ucbrise/opaque#4]
The least squares test seems to crash when running when I run `OpaqueMultiplePartitionSuite`.
See [this branch](https://github.com/karthik-shanmugam/opaque/tree/least-squares-crashing) to recreate quickly.

![screenshot from 2017-03-17 17 30 45](https://cloud.githubusercontent.com/assets/7821859/24067288/c7dd4788-0b37-11e7-8670-1640b80101e2.png)

**Comment by wzheng** [comment]
Temporary fix for now.
