### ISSUE TITLE
Security: No boundary check on `ocall_malloc`

### ISSUE THREAD

**Issue by Eadom** [ucbrise/opaque#66]
```cpp
// EDL
void ocall_malloc(size_t size, [out] uint8_t **ret);

// Implementation
void ocall_malloc(size_t size, uint8_t **ret) {
    *ret = static_cast<uint8_t *>(malloc(size));
}
```

`uint8_t **ret` could be a pointer to memory in enclave. It could casue a arbitrary memory write in enclave.

Fix：

Add a wrapper function of `ocall_malloc`, checking the returned value with `sgx_is_inside_enclave`/``sgx_is_outside_enclave``. There is a sample below.

```cpp
void wrapper_ocall_malloc(size_t size, uint8_t **ret) {
    ocall_malloc(size, ret);
    if (sgx_is_inside_enclave(*ret, size)) {
        // error
    }
}
```

**Comment by ankurdave** [comment]
Thanks for reporting this! I made PR #67, which implements your suggestion with one change: the wrapper is named `ocall_malloc` while the raw ocall is renamed to `unsafe_ocall_malloc` to reduce the chance that it is accidentally called in future code.
