### ISSUE TITLE
Can't fetch data from aws

### ISSUE THREAD

**Issue by zzzzzzch** [ucbrise/opaque#80]
Hi, guys! Sorry to bother you.

I tried to fetch 1millon data using fetch-data.sh from aws. But I got
> ERROR: S3 error: 403 (AccessDenied): Access Denied

Is the data no longer available or it's only my aws wrongly configured? 
Thanks!

**Comment by ankurdave** [comment]
Oops, they were set to private. I just made them public.

**Comment by zzzzzzch** [comment]
Thanks for your reply!
I can sync the data now, but the data is not writable.
> WARNING: ./bdb/rankings/1million/000000_0.txt not writable: Operation not permitted
